---
title: "Triksing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(scipen=999)

library(knitr)
library(googlesheets4)
library(tidyverse)
library(MASS)
library(pscl)
library(kableExtra)

fotball<- sheets_read("1CAmqpuF6ViHyYRhVZjbIuxZ4uXg4xi53_xm1Yz0KuoA", col_names = FALSE)
fotball$K<-1

fotball_lang <- fotball %>%
  pivot_longer(-K, names_to = "test", values_to = "antall") %>% 
  mutate(test_num = as.numeric(str_remove(test, '...'))) %>% 
  mutate(antall_2 = antall - 2) %>% 
  group_by(test_num) %>% 
  mutate(n = cumsum(K)) %>% 
  mutate(person = case_when(test_num %in% c(6, 9, 14) ~ "Olaf",
                        TRUE ~ "Mari")) %>% 
  filter(person == "Mari") %>% 
  ungroup() %>% 
  drop_na()

tabell_data <- fotball_lang %>% 
  group_by(person, antall) %>% 
  summarise(n = n())

```

```{r hist, fig.height = 8, fig.width = 8, echo=FALSE}

ggplot(tabell_data, aes(antall, n)) +
  geom_bar(stat = "identity", position = 'dodge', fill = 'red') + 
  theme_light() +   
  scale_x_continuous("antall", breaks = seq(2,max(tabell_data$antall),1))
  
```


```{r dist, fig.height = 8, fig.width = 8, echo=FALSE}
m1 <- glm(antall_2 ~ factor(test) + n , data = fotball_lang, family = "poisson")
m2 <- glm.nb(antall_2 ~ factor(test) + n, data = fotball_lang)

pred.m2 <- predprob(m2) %>% colMeans
pred.m1 <- predprob(m1) %>% colMeans

df <- data.frame(x = 0:max(fotball_lang$antall_2), NegBin = pred.m2)

obs <- table(fotball_lang$antall_2) %>% prop.table() %>% data.frame #Observed
obs <- obs %>% 
  mutate(Var1 = as.numeric(levels(Var1))[Var1])
names(obs) <- c("x", 'Observed')

comb <- merge(obs, df, by = 'x', all = T)
comb[is.na(comb)] <- 0

mm <- pivot_longer(comb, -x, names_to = 'Model', values_to = 'prob') 

ggplot(mm, aes(x = x, y = prob, group = Model, col = Model)) +
 geom_line(aes(lty = Model), lwd = 1) + 
 theme_light() +
 scale_x_continuous(breaks = seq(0,max(tabell_data$antall)-2,1),
                    labels = seq(2,max(tabell_data$antall),1)) +
 theme(legend.position="bottom")
 
```

```{r tabell, echo = FALSE}

m2 <- glm.nb(antall_2 ~ K, data = fotball_lang)

N <- table(fotball_lang$antall_2)  %>% data.frame

N <- N %>% 
  mutate(Var1 = as.numeric(levels(Var1))) %>% 
  mutate(Var1 = Var1 + 2)

names(N) <- c('x', 'N')

obs <- obs %>% 
  mutate(x = x + 2) %>%
  mutate(Observed = Observed * 100)

x <- 0:(max(tabell_data$antall)+1)
probtable <- as.data.frame((dnbinom(x, size = m2$theta, mu = exp(m2$coefficients[1]))) * 100) %>%
  rownames_to_column() %>%
  mutate(rowname = as.numeric(rowname) + 1)

names(probtable) <- c("Antall", "Sannsylighet")

probtable <- probtable %>%
  left_join(obs, by = c('Antall' = 'x')) %>%
  left_join(N, by = c('Antall' = 'x')) %>% 
  mutate(Sannsylighet = format(Sannsylighet, digits = 1),
         Observed = format(Observed, digits = 2))

probtable <- t(probtable)

probtable %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```



```{r over_tid, fig.height = 8, fig.width = 8, echo=FALSE}

snitt <- fotball_lang %>% 
  group_by(test_num) %>% 
  summarize(sum = sum(antall),
            gjennomsnitt = mean(antall),
            se = sd(antall)/sqrt(n()),
            median = median(antall)) %>% 
  mutate(Repetisjon = as.numeric(as.factor(test_num)))
 
ggplot(snitt, aes(x=Repetisjon, y=gjennomsnitt)) +
  geom_errorbar(aes(ymin=gjennomsnitt-(1.96*se), ymax=gjennomsnitt+(1.96*se)), colour="black", width=.2) +
  geom_line(color = 'red', size = 1.2) +
  geom_hline(yintercept = mean(fotball_lang$antall), color = 'blue', size = 1.2) +
  geom_hline(yintercept = mean(fotball_lang$antall) + (1.96*sd(fotball_lang$antall)/sqrt(nrow(fotball_lang))), 
             color = 'blue', size = 0.2) +
  geom_hline(yintercept = mean(fotball_lang$antall) - (1.96*sd(fotball_lang$antall)/sqrt(nrow(fotball_lang))), 
             color = 'blue', size = 0.2) +
  theme_light() +
  scale_x_continuous(breaks = seq(1,nrow(snitt),1))

  

```

Antall forsøk tilsammen: `r nrow(fotball_lang)`

Snitt: `r exp(m2$coefficients[1])+2`

Theta: `r m2$theta`


```{r lowess, fig.height = 8, fig.width = 8, echo=FALSE}

lowess <- fotball_lang %>% 
  arrange(test_num, n) %>% 
  rownames_to_column() %>% 
  mutate(rowname = as.numeric(rowname))

ggplot(lowess, aes(x = rowname, y = antall)) +
  geom_point() +
  geom_smooth(span = 0.2)




```

